version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: portblock
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: murphships
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/murphships/portblock"
    description: "mock APIs that actually behave like real ones"
    license: "MIT"
    test: |
      system "#{bin}/portblock", "--help"
    install: |
      bin.install "portblock"

release:
  github:
    owner: murphships
    name: portblock
